ALTER TABLE `payment`
    MODIFY COLUMN `amount_value` DECIMAL (19, 2) NOT NULL,
    MODIFY COLUMN `amount_currency` VARCHAR (3) NOT NULL,
    MODIFY COLUMN `status` VARCHAR (16) DEFAULT 'INITIATED',
    MODIFY COLUMN `created_at` TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP (6),
    MODIFY COLUMN `deleted` BIT (1) DEFAULT 0,
    MODIFY COLUMN `version` BIGINT DEFAULT 0;