server:
  http_listen_port: 3100
  log_level: info
  grpc_listen_port: 0

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  wal:
    enabled: true
  chunk_idle_period: 5m
  max_chunk_age: 1h

limits_config:
  max_streams_per_user: 0
  enforce_metric_name: false
  allow_structured_metadata: false

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor