server:
  http_listen_port: 3200
  grpc_listen_port: 43170

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
    final_sleep: 0s

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal